<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>14d5157d-2f84-40d9-94c2-504ccb1b581c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenIddict" Version="7.0.0" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.0.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.0.0" />
    <PackageReference Include="OpenIddict.Server" Version="7.0.0" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" Version="7.0.0" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" Version="7.0.0" />
  </ItemGroup>

</Project>
